<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransactionValidation.Configuration\TransactionValidation.Configuration.csproj" />
    <ProjectReference Include="..\TransactionValidation.Core\TransactionValidation.Core.csproj" />
    <ProjectReference Include="..\TransactionValidation.Integration\TransactionValidation.Integration.csproj" />
    <ProjectReference Include="..\TransactionValidation.Messaging\TransactionValidation.Messaging.csproj" />
  </ItemGroup>
</Project>
