<Project Sdk="Microsoft.NET.Sdk.Web">
	<ItemGroup>
		<PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="RabbitMQ.Client" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.Console" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TransactionValidation.Configuration\TransactionValidation.Configuration.csproj" />
		<ProjectReference Include="..\TransactionValidation.Messaging\TransactionValidation.Messaging.csproj" />
	</ItemGroup>
</Project>
